title: Exploring Existence
author:
  name: Roy Straub
  email: webmaster@rstraub.com

description: 
  Essays on programming, thought, reading, writing and anything else brightening my existence.
domain: rstraub.com
url: https://rstraub.com
permalink: /:slug

sass:
  quiet_deps: true
  silence_deprecations: [import]

show_drafts: false

# Build settings
theme: minima
minima:
  skin: auto
  # Needs some manual work
  show_excerpts: false
  social_links:
    - title: GitHub Profile
      icon: github
      url: "https://github.com/rstraub"
    - title: LinkedIn Profile
      icon: linkedin
      url: "https://linkedin.com/in/r-straub"
#  nav-pages:
#    - test.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true

exclude:
- CNAME
- docker-compose.yml
- .gitignore
- .obsidian
- .idea
- .vscode
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
