# Site
name: "CodeCraftr"
title: "CodeCraftr"
description: "Exploring the Art of Coding"
logo: 'assets/images/terminal-icon.png'
favicon: 'assets/images/terminal-icon.png'
baseurl: ''
google_analytics: ''
disqus: ''
include: [ "_pages" ]
permalink: /:title/

# Authors
authors:
  roy:
    name: Roy
    display_name: Roy Straub
    avatar: 'assets/images/avatar.JPG'
    email: wowthemesnet@gmail.com
    web: https://rstraub.github.io
    description: "Avid lover of great Software Craftsmanship. Practicing the Art of Coding since 2011."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [ changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, docker-compose.yml ]
