# Site
name: "CodeCraftr ⚒️"
title: "CodeCraftr ⚒️"
tagline: "Exploring the Art of Coding"
description: "A blog dedicated to exploring craftsmanship in Software Development"
logo: "assets/images/terminal-icon.png"
favicon: "assets/images/terminal-icon.png"
baseurl: ""
google_analytics: "G-VGRRHKG9RD"
disqus: "codecraftr"
include: ["_pages"]
permalink: /:title/
url: https://www.codecraftr.nl
author: Roy Straub
social:
  name: Roy Straub
  links:
    - https://twitter.com/CCraftr
    - https://www.linkedin.com/in/r-straub/
    - https://github.com/rstraub

twitter:
  username: CCraftr
  card: summary

# Authors
authors:
  Roy Straub:
    name: Roy Straub
    display_name: Roy Straub
    avatar: "assets/images/avatar.JPG"
    web: /about
    twitter: https://twitter.com/CCraftr
    description: "Craftsmanship Lead @ CodeSquad. Passionate about Software Craftsmanship. Interested in subjects such as Clean Code, Domain Driven Design and Extreme Programming. Happily coding since 2010."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-redirect-from

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude:
  [
    changelog.md,
    LICENSE.txt,
    README.md,
    Gemfile,
    Gemfile.lock,
    docker-compose.yml,
    docker-compose-build.yml,
  ]
