version: '3'

services:
    jekyll:
        image: docker.io/jekyll/jekyll:latest
        command: jekyll serve --force_polling --livereload --drafts
        environment:
            - JEKYLL_ENV=docker
        ports:
            - 4000:4000
            - 35729:35729
        volumes:
            - .:/srv/jekyll
